export enum INJECTION_TOKEN {
  CHAT_BOT_SERVICE = 'CHAT_BOT_SERVICE',
}

export enum REPOSITORY_INJECTION_TOKEN {
  CONVERSATION_REPOSITORY = 'CONVERSATION_REPOSITORY',
  USERS_REPOSITORY = 'USERS_REPOSITORY',
  DEVICE_REPOSITORY = 'DEVICE_REPOSITORY',
}
