import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ReduxProvider from "@/redux/provider";
import Spinner from "@/components/spinner";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} antialiased mx-auto min-h-screen`}
    >
      <div className="bg-[7ddaf7] min-h-screen w-full">
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger />
          <div className="w-full mx-auto">
            <Header />
            {children}
            <Footer />
          </div>
        </SidebarProvider>
      </div>
    </div>
  );
}
